    # This is a comment
    title = "My Project"
    version = "1.0.0"

    [database]
    type = "PostgreSQL"
    host = "localhost"
    port = 5432

    [[users]]
    name = "Alice"
    id = 1
    
    [[users]]
    name = "Bob"
    id = 2